export { ArticlesList } from './ui/ArticlesList/ArticlesList'
export { ArticleDetails } from './ui/ArticleDetails/ArticleDetails'
export type { Article } from './model/types/article'
export type { ArticleDetailsSchema } from './model/types/articleDetailsSchema'
export { articleDetailsReducer } from './model/slice/articleDetailsSlice'
export { ArticleView } from 'entities/Article/model/types/article'
